title: My Public Journal
description: Documenting my journey to Stanford, tech success, and creating my dream life
theme: jekyll-theme-minimal

# About
author: Ishaani Jain
timezone: America/Los_Angeles

# Settings
show_downloads: false
