title: My Public Journal
description: My personal blog/journal of whatever I want to talk about. I have no rules for me on this blog, something in which I can be raw in, myself in, 
and talk about stuff that truly makes me happy!
theme: jekyll-theme-minimal 



# About
author: Anon
timezone: America/Los_Angeles

# Settings
show_downloads: false
